config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :arts, only: %i[index new create edit update destroy]

  resources :requests, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many_attached :photos
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @arts = Art.all
    @request = Request.new
    @arts = Art.paginate(page: params[:page], per_page: 10)
  end

  def new
    @art = Art.new
  end

  def create
    @art = Art.new(art_params)
    if @art.save
      redirect_to arts_path
    else
      render 'new'
    end
  end

  def edit
    @art = Art.find(params[:id])
  end

  def update
    @art = Art.find(params[:id])
    if @art.update(art_params)
      if params[:art][:photos].present?
        params[:art][:photos].each do |photo|
          @art.photos.attach(photo)
        end
      end
      redirect_to arts_path
    else
      render 'edit'
    end
  end

  def destroy
    @art = Art.find(params[:id])
    @art.destroy
    redirect_to arts_path
  end

  private

  def art_params
    params.require(:art).permit(:name, :price, :size, photos:[])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @request = Request.new
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      RequestMailer.send_email(@request).deliver_now
      redirect_to art_path, notice: "Request sent!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def request_params
    params.require(:request).permit(:email, :name, :content, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arts/_art_card.html.erb
<div class="artpiece d-flex flex-column align-items-center">
  <h4 class="text-mybeige"><%= art.name %></h2>
  <div class="col-md-6 d-flex justify-content-center">
    <div class="wrapper" data-controller="carousel">
      <i id="left" class="fa-solid fa-angle-left" data-action="click->carousel#scrollLeft"></i>
      <div class="carousel" data-target="carousel.carousel">
        <% art.photos.each do |photo| %>
          <%= image_tag(photo, { alt: "alttext", class: "img-carousel", draggable: false }) %>
        <% end %>
      </div>
      <i id="right" class="fa-solid fa-angle-right" data-action="click->carousel#scrollRight"></i>
    </div>
  </div>

  <div class="art-info d-flex align-items-center">
    <div class="art-details">
      <p><%= art.price %>€</p>
      <p><%= art.size %>cm</p>
    </div>
    <% if user_signed_in? %>
      <%= link_to edit_art_path(art), class: "icons" do %><i class="fa-solid fa-wrench"></i><% end %>
    <% end %>
    <button type="button" title="Request" class="border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#new_request_modal">
      <i class="fa-solid fa-envelope"></i>
    </button>
  </div>
</div>

<%= render "modal", request: @request %>

app/views/arts/_modal.html.erb
<div class="modal fade" id="new_request_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content align-items-center p-5">
      <div class="modal-header">
        <h5 class="modal-title">Request this piece</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [@request] do |f|%>
        <div class="form-inputs">
          <%= f.input :email, label: false, placeholder: "Your Email" %>
          <%= f.input :name, label: false, placeholder: "Your Name" %>
          <%= f.input :subject, label: false, placeholder: "Subject" %>
          <%= f.input :content, label: false, placeholder: "Your Message" %>
        </div>
        <div class="form-actions d-flex">
          <%= f.submit "Send", class: "btn-main" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/arts/edit.html.erb
<%= simple_form_for [@art] do |f|%>
  <div class="form-inputs">
    <%= f.input :name, label: false, placeholder: "Name" %>
    <%= f.input :size, label: false, placeholder: "Size" %>
    <%= f.input :price, label: false, placeholder: "Price" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, label: false, placeholder: "Choose photos" %>
    <div class="form-actions">
    <%= f.submit "Update", class: "btn-main" %>
  </div>
  </div>
<% end %>

<%= link_to "Delete this piece", art_path(@art), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this piece?" } %>

app/views/arts/index.html.erb
<div class="portfolio-container">
  <div class="header d-flex justify-content-between">
    <%= image_tag "logo1.png", alt: "logo", class: "logo" %>
    <h3 class="text-mybeige">Portfolio</h3>
    <div class="page-navigation d-flex align-items-center">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </div>
  </div>
  <div class="line"></div>

  <p class="page-nav-top">Showing <%= @arts.offset_value + 1 %> - <%= @arts.offset_value + @arts.length %> of <%= @arts.total_entries %> results</p>

  <% if user_signed_in? %>
    <%= link_to new_art_path, class: "icons ms-4" do %><i class="fa-solid fa-plus"></i><% end %>
  <% end %>

  <% @arts.each_with_index do |art, index| %>
    <% if index % 2 == 0 %>
      <div class="row ms-0 me-0 art-container">
    <% end %>

    <div class="col-md-6 d-flex justify-content-center">
      <%= render "art_card", art: art %>
    </div>

    <% if index % 2 == 1 || index == @arts.size - 1 %>
      </div>
    <% end %>
  <% end %>

</div>

<% if user_signed_in? %>
  <%= link_to destroy_user_session_path, method: :delete, data:{ turbo: :false }, class: "icons ms-4" do %><i class="fa-solid fa-door-open"></i><% end %>
<% end %>

<div class="pagination d-flex justify-content-center mb-5 page-nav">
  <%= will_paginate @arts %>
</div>

app/views/arts/new.html.erb
<%= simple_form_for [@art] do |f|%>
  <div class="form-inputs">
    <%= f.input :name, label: false, placeholder: "Name" %>
    <%= f.input :size, label: false, placeholder: "Size" %>
    <%= f.input :price, label: false, placeholder: "Price" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, label: false, placeholder: "Choose photos" %>
    <div class="form-actions">
    <%= f.submit "Create", class: "btn-main" %>
  </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetraWartmark</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <div class="main-container" id="top">
    <div class="header d-flex justify-content-between">
      <div>
        <%= image_tag "logo1.png", alt: "logo", class: "logo" %>
      </div>
      <div class="page-navigation d-flex justify-content-between align-items-center">
        <div class="me-5">
          <%= link_to "Portfolio", arts_path, class: "nav-link" %>
        </div>
        <div class="me-5" data-controller="scroll-into">
          <%= link_to "About", "#about", class: "nav-link", data: {action: "click->scroll-into#scrollIntoAbout"} %>
        </div>
        <div data-controller="scroll-into">
          <%= link_to "Contact", "#contact", class: "nav-link", data: {action: "click->scroll-into#scrollIntoContact"} %>
        </div>
      </div>
    </div>
    <div class="line"></div>
    <div class="card-div d-flex justify-content-around">
      <div><%= image_tag "pic1.png", alt: "alttext", class: "card-home" %></div>
      <div><%= image_tag "pic2.png", alt: "alttext", class: "card-home" %></div>
      <div><%= image_tag "pic3.png", alt: "alttext", class: "card-home" %></div>
      <div><%= image_tag "pic4.png", alt: "alttext", class: "card-home" %></div>
      <div><%= image_tag "pic5.png", alt: "alttext", class: "card-home" %></div>
    </div>
    <div class="content-div">
      <h1 class="text-mybeige mb-3">Petra Wartmark Studios</h1>
      <p>I find inspiration in the environment and people around me. Not the particular objects in itself but the experiences and emotional connection. The subtle shifts in seeing the world around me heavily influence my work.</p>
    </div>
  </div>
  <div class="about-container" id="about">
    <h2>About</h2>
    <p class="about-text">I didn't define myself as a creative person, but a couple of years ago, something changed. I found the urge to express myself and expand my creativity. I began painting in search of self-expression and more profound connection with life and myself.</p>
    <p class="about-text">Love working in large scale and using instinct motion to direct my work compositionally and apply my mark making. Mainly working with acrylics while utilizing both traditional and found objects or things within reach as tools to interact with on canvas. Passionate about the unique and integral impact artwork can have within a space.</p>
  </div>
  <div class="contact-container" id="contact">
    <div></div>
    <div class="justify-content-center">
      <h3 class="text-mybeige mb-3">Contact</h3>
      <%= simple_form_for [@request] do |f|%>
        <div class="form-inputs">
          <%= f.input :email, label: false, placeholder: "Your Email" %>
          <%= f.input :name, label: false, placeholder: "Your Name" %>
          <%= f.input :content, label: false, placeholder: "Your Message" %>
        </div>
        <div class="form-actions">
          <%= f.submit "Send", class: "btn-main" %>
        </div>
      <% end %>
    </div>
    <div class="social-links">
      <a href="https://www.instagram.com/petrawartmark/" target="_blank"><i class="fa-brands fa-instagram"></i></a>
    </div>
  </div>
  <footer class="main-footer" data-controller="scroll-into"><button class="arrow-up" data-action="click->scroll-into#scrollIntoTop" data-controller="hide-on-top" data-hide-on-top-target="arrow" title="Return to top"><i class="fa-solid fa-circle-arrow-up"></i></button></footer>
</div>